{% set name = "simplecrop" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openmodelingfoundation/SimpleCrop/archive/{{ version }}.tar.gz
  sha256: a87241369fb766b3a75e26f687e57d47eb0babf6e56f52820b0d0e238108762b

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}  # [win]
    - cmake
  host:
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}  # [win]

test:
  source_files:
    - data
  commands:
    - mkdir output
    - simplecrop


about:
  home: https://github.com/openmodelingfoundation/SimpleCrop
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: An approach for modular crop model development
  description: |
    An approach for modular crop model development
  doc_url: https://github.com/openmodelingfoundation/SimpleCrop
  dev_url: https://github.com/openmodelingfoundation/SimpleCrop

extra:
  recipe-maintainers:
    - mcflugen
    - cpritcha
